### ISSUE TITLE
struct with field *int having zero do not return properly

### ISSUE THREAD

**Issue by Bysmyyr** [recoilme/pudge#14]
Hi! Thanks for nice lib. I found An issue. Code tells everything

```
	type  test struct {
		A *int
	}

	i := 0
	p := test{A: &i}

	pudge.Set("a", "a", p)

	re := test{}
	pudge.Get("a","a", &re)

	log.Print(re.A) // prints <nil>, should print pointer (to zero)

```

**Comment by recoilme** [comment]
Sorry. It's by design in go encoders/decoders: https://github.com/golang/go/issues/4609
"A consequence of the design. Perhaps unfortunate, but not going to change." // Rob Pike

**Comment by Bysmyyr** [comment]
thanks for the info, thats sad. lets see how to bypass that
