### ISSUE TITLE
Не сохраняется часть данных со StoreMode = 2

### ISSUE THREAD

**Issue by nxshock** [recoilme/pudge#4]
Возьмём, к примеру, следующую программу, сохраняющая данные в несколько файлов:

<details><summary>Код с StoreMode = 0</summary>

```
package main

import (
	"fmt"
	"log"

	"github.com/recoilme/pudge"
)

func main() {
	pudge.DefaultConfig.StoreMode = 0

	for i := 0; i < 100000; i++ {
		fileName := fmt.Sprintf("data/%d", i%5)
		err := pudge.Set(fileName, i, i)
		if err != nil {
			log.Fatalln(err)
		}
	}

	err := pudge.CloseAll()
	if err != nil {
		log.Fatalln(err)
	}
}
```

</details>

Получаем на выходе 5 файлов с данными по 131 КБ и 5 файлов по 469 КБ с индексами.

Теперь поменяем `StoreMode = 2`, и попробуем выполнить тот же код:

<details><summary>Код с StoreMode = 2</summary>

```
package main

import (
	"fmt"
	"log"

	"github.com/recoilme/pudge"
)

func main() {
	pudge.DefaultConfig.StoreMode = 2

	for i := 0; i < 100000; i++ {
		fileName := fmt.Sprintf("data/%d", i%5)
		err := pudge.Set(fileName, i, i)
		if err != nil {
			log.Fatalln(err)
		}
	}

	err := pudge.CloseAll()
	if err != nil {
		log.Fatalln(err)
	}
}
```

</details>

В результате получаю заполенным только один файл и данными и файл с индексом (который цифрой 0), а остальные 4 файла пустые - данные в них не сохраняются.

**Comment by recoilme** [comment]
Скорее всего вы не вызвали Close или CloseAll (эти функции надо вызывать всегда перед выходом, в любом режиме)
В ин-мемори режиме сохранение осуществляется при закрытии

**Comment by recoilme** [comment]
Спасибо! [Пофиксил](https://github.com/recoilme/pudge/commit/90bf9468ef7219be6e2ab6fd316f05c69ae2fc29)
