### ISSUE TITLE
После удаления по ключу, в индексном файле остаются удаленные ключи

### ISSUE THREAD

**Issue by happytuxi** [recoilme/pudge#5]
После удаления по ключу, в индексном файле (*.idx) остаются удаленные ключи.

**Comment by recoilme** [comment]
Запись о удалении, добавляется в конец файла, это не баг, но возможно стоит затирать

**Comment by happytuxi** [comment]
Это влияет только на размер? на скорость поиска не влияет?

**Comment by recoilme** [comment]
Да, только на размер
