### ISSUE TITLE
StoreMode - memory only

### ISSUE THREAD

**Issue by begetan** [recoilme/pudge#6]
I would like to use this nice library as an in-memory cache only.
There are only two modes and both are creating the files.
It is unnecessary in memory only mode.

`StoreMode    int // 0 - file first, 2 - memory first(with persist on close)`

I suggest to introduce third mode: **memory only**

In this mode files shoudn't be opened at all, so path will be ignored 
and no need to call _db.CloseAll_

**Comment by recoilme** [comment]
Hello, did you try don't call CloseAll if you don't need persistence? That's ugly but may works

**Comment by recoilme** [comment]
@begetan  Roman, take a look please: https://github.com/recoilme/pudge/commit/4721544b688e32ba98bad1d7abce8a37ab731c2d

Example: https://github.com/recoilme/pudge/blob/master/examples/examples.go#L82
Test: https://github.com/recoilme/pudge/blob/master/pudge_test.go#L534

**Comment by begetan** [comment]
@recoilme 

So providing empty filename to pudge.Open() makes configuration completely in-memory without disk files. Greate idea, thanks!
